version: "3"
services:
  jenkins:
    image: "jenkins/jenkins:lts"
    restart: "always"
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - "8080:8080"
    volumes:
      - "./jenkins_home:/var/jenkins_home"
      - "/usr/bin/docker:/usr/bin/docker"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/lib64/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7"
